FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY models/ /app/models/

COPY Diabetes-Application/ /app/

ENV PYTHONUNBUFFERED=1

EXPOSE 5000

CMD ["python", "app.py"]